OPTIONS = -Wall -Wextra -Wpedantic -Werror -O2 -std=c++17

all: main_1 main_2 main_3

main_1: main_1.cc
	g++ main_1.cc -o main_1  $(OPTIONS)

main_2: main_2.cc
	g++ main_2.cc -o main_2  $(OPTIONS)

main_3: main_3.cc
	g++ main_3.cc -o main_3  $(OPTIONS)

clean:
	rm main_1 main_2 main_3